story/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_view

from . import views


urlpatterns=[
    path("login/",auth_view.LoginView.as_view(template_name="story/login.html"),name="login"),
    path("logout/",auth_view.LogoutView.as_view(),name="logout"),
    path("",views.Home.as_view(),name="home"),
    path('my_stories/',views.MyStories.as_view(),name='my_stories'),
    path('story/<int:pk>/',views.StoryDetail.as_view(),name="story_detail"),
    path('dashboard/',views.Dashboard.as_view(),name='dashboard'),
    path('story/add/',views.AddStory.as_view(),name='add_story'),
    path('add/comment/<int:pk>/',views.StoryComment.as_view(),name='add_comment'),
    path('story/<int:pk>/update/',views.StoryUpdate.as_view(),name='update_story'),
    path('story/<int:pk>/delete/',views.StoryDelete.as_view(),name='delete_story'),
    path('true/<int:pk>/',views.true_story,name='true_story'),
    path('false/<int:pk>/',views.false_story,name='false_story'),

    

]   

true_or_false/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import TokenVerifyView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api-auth/',include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] 

story/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from django.db.models.fields import BooleanField, CharField, IntegerField, TextField
from django.contrib.auth.models import User
from django.db.models.fields.related import ForeignKey

class Story(models.Model):
    text = models.TextField(max_length=2000,unique=True,default='')
    t = models.ManyToManyField(User,related_name='vote_true')
    f = models.ManyToManyField(User,related_name='vote_false')
    ans = models.BooleanField(default=False)
    author = models.ForeignKey(User,to_field='username',on_delete=models.CASCADE)

    def total_t(self):
        return self.t.count()

    def total_f(self):
        return self.f.count()
    

    def __str__(self):
        return f'{self.text[:10]}... a napisao je {self.author}' 
    
    def __repr__(self):
        return 'Stories' 

class Comment(models.Model):
    text = models.CharField(max_length=550,unique=True,default='')
    story = models.ForeignKey(Story,on_delete=models.CASCADE) #       objava = models.ForeignKey("Objava",on_delete=models.DO_NOTHING) 
    author=models.ForeignKey(User, to_field='username',on_delete=models.CASCADE,default="")
    #author=ForeignKey(User,on_delete=models.DO_NOTHING,default="") uzima samo user_ids

story/forms.py
from django import forms
from .models import Story,Comment

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = [
            'text',
            'ans',
            'author',
        ]
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'text',
            'author',
            'story'
        ]

story/views.py
from django.db.models.fields.related import ForeignKey
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User
from django.views.generic import View,ListView,UpdateView,DetailView,FormView,DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy,reverse


from .models import Story,Comment
from .forms import StoryForm,CommentForm


@method_decorator(login_required,name='dispatch')
class Home(ListView):
    model = Story
    context_object_name = 'stories'
    queryset = Story.objects.all()
    template_name = 'story/stories.html'
    ordering = 'id'
    paginate_by = '10'

@method_decorator(login_required,name='dispatch')
class MyStories(ListView):
    model = Story
    context_object_name = 'my_stories'
    template_name = 'story/my_stories.html'
    ordering = '-id'
    paginate_by = '10'

    def get_queryset(self):
        return Story.objects.filter(author=self.request.user)


class StoryDisplay(DetailView):
    model = Story
    context_object_name = 'story'
    def get_object(self):
        object= super(StoryDisplay,self).get_object()
        object.save()
        return object

    def get_context_data(self,**kwargs):
        context = super(StoryDisplay,self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(story=self.get_object())
        this_story=super(StoryDisplay,self).get_object()
        total_true=this_story.total_t()
        total_false=this_story.total_f()       
        context['total_true']=total_true
        context['total_false']=total_false
        context['form'] = CommentForm
        return context

@method_decorator(login_required,name='dispatch')
class StoryComment(FormView):
    form_class = CommentForm
    template_name = 'story/story_detail.html'

    def form_valid(self,form):
        form.instance.author= self.request.user
        story = Story.objects.get(pk=self.kwargs['pk'])
        form.instance.story = story
        form.save()
        return super(StoryComment,self).form_valid(form)
    
    def get_success_url(self): 
        return reverse('story_detail',kwarg={'pk':self.kwargs['pk']})

class StoryDetail(View):
    def get(self,request,*args, **kwargs):  
        view = StoryDisplay.as_view(
            template_name = 'story/story_detail.html'
        )
        return view(request,*args, **kwargs)

    def post(self,request,*args, **kwargs):
        view = StoryComment.as_view(
            template_name = 'story/story_detail.html'
        )
        return view(request,*args, **kwargs)

@method_decorator(login_required,name='dispatch')
class Dashboard(View):
    def get(self,request,*args, **kwargs):
        view = Home.as_view(
            template_name = 'story/admin.html'
        )
        return view(request,*args, **kwargs)


class StoryUpdate(UpdateView):
    model = Story
    fields = ('text','ans')

    def get_success_url(self):
        return reverse_lazy('my_stories')

class StoryDelete(DeleteView):
    model = Story
    success_url = reverse_lazy('dashboard')
    
@method_decorator(login_required,name='dispatch')
class AddStory(FormView):
    form_class = StoryForm
    template_name = 'story/story_form.html'

    def form_valid(self,form):
        form.instance.author= self.request.user
        form.save()
        return super(AddStory,self).form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('my_stories')

def true_story(request,pk):
    story = get_object_or_404(Story, id=request.POST.get('true_story_id'))
    story.t.add(request.user)
    return HttpResponseRedirect(reverse('story_detail', args=[str(pk)]))

def false_story(request,pk):
    story = get_object_or_404(Story, id=request.POST.get('false_story_id'))
    story.f.add(request.user)
    return HttpResponseRedirect(reverse('story_detail', args=[str(pk)]))

story/templates/story/admin.html
{% extends 'base.html' %}
{% block breadcrumb %}{{ block.super }} > Admin {% endblock %}
{% block content %}
    {% include 'nav.html' %}
    {% for story in stories %}

        <div id="container">
        <div class="d-flex justify-content-end"><p>{{story.author}}</p></div>
        <div class="d-flex justify-content-center"><p>{{story.text}}</p></div>
        <div class="row d-flex justify-content-center">
            <div class="col-sm-4" style="text-align: center; margin-left: 80%;"><a href="/story/{{forloop.counter}}" class="btn" style="color: rgb(248, 207, 207); background-color: rgba(248, 64, 58, 0.274);">Comments</a></div>
        </div>
        <div class="col-sm row" style="text-align: center;justify-content: center;">
        </div>
        <div class="col-sm row d-flex" style="text-align: center;">
            <div class="col-sm-1 justify-content-start"></div>
            <a href="{% url 'update_story' story.pk %}" class="btn btn-primary col-sm-3">Update</a>
            <div class="col-sm-1 justify-content-end"></div>
            <a href="{% url 'delete_story' story.pk %}" class="btn btn-primary col-sm-3">Delete</a>
        </div>
        </div>
    {% empty %}    
        <div id="container2">
            <div class="d-flex justify-content-center"><p>There are no stories yet.</p></div>
        </div>
    {% endfor %}

    {% include 'story/pagination_links.html' %}

{% endblock %}

story/templates/story/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>True or false</title>
   <link rel="stylesheet" href="{% static 'story/css/style.css' %}"> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>

<body style="background-color: black;">
{% block content %}

{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

story/templates/story/login.html
{% extends 'base.html' %}
{% block content %}
{% include 'nav.html' %}

<div class="container" style="color: white;">
    <div class="form login-form d-flex justify-content-center">
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="Login"></p>
        </form>
    </div>
</div>

{% endblock %}

story/templates/story/my_stories.html
{% extends 'base.html' %}
{% block content %}
{% include 'nav.html' %}
    {% for story in my_stories %}

        <div  id="container">
        <div class="d-flex justify-content-end"><p>{{story.author}}</p></div>
        <div class="d-flex justify-content-center"><p>{{story.text}}</p></div>
        <div class="row d-flex justify-content-center">
            <div class="col-sm-4" style="text-align: center; margin-left: 80%;"><a href="/story/{{forloop.counter}}" class="btn" style="color: rgb(248, 207, 207); background-color: rgba(248, 64, 58, 0.274);">Comments</a></div>
        </div>
        </div>

    {% empty %}
        
        <div id="container2">
            <div class="d-flex justify-content-center"><p>There are no stories yet.</p></div>
        </div>
        
    {% endfor %}

    {% include 'story/pagination_links.html' %}

{% endblock %}

story/templates/story/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="">True or False</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">All stories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my_stories' %}">My stories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_story' %}">Share your story</a>
        </li>
        {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'logout' %}" class="btn btn-primary col-sm">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'login' %}" class="btn btn-primary col-sm">Login</a>
        </li>
        {% endif %}
<!--        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li> -->
      </ul>
      
    </div>
  </nav>

story/templates/story/pagination_links.html
<div class="pagination">
    <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    <span class="current">
       Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}  
    </span> 
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

story/templates/story/stories.html
{% extends 'base.html' %}
{% block content %}
    {% include 'nav.html' %}
    {% for story in stories %}

        <div id="container">
        <div class="d-flex justify-content-end"><p>{{story.author}}</p></div>
        <div class="d-flex justify-content-center"><p>{{story.text}}</p></div>
        <div class="row d-flex justify-content-center">
            <div class="col-sm-4" style="text-align: center; margin-left: 80%;"><a href="/story/{{forloop.counter}}" class="btn" style="color: rgb(248, 207, 207); background-color: rgba(248, 64, 58, 0.274);">Comments</a></div>
        </div>
        </div>
    {% empty %}    
        <div id="container2">
            <div class="d-flex justify-content-center"><p>There are no stories yet.</p></div>
        </div>
    {% endfor %}

    {% include 'story/pagination_links.html' %}

{% endblock %}

story/templates/story/story_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% include 'nav.html' %}
<div id="container" style="background-color: black;">
  <form action="" method="POST">
    {% csrf_token %}
    <div class="d-flex justify-content-center"><p>Are you sure?</p></div>    
    <div class="col-auto my-2">
      <button type="submit" class="btn btn-secondary" style="margin-left: 94%;" value="yes">Yes!</button>
    </div>     
  </form>
</div>
{% endblock %}

story/templates/story/story_detail.html
{% extends 'base.html' %}
{% block content %}
{% include 'nav.html' %}
    <div id="container">
      <a href="/" class="btn btn-primary col-sm">Go back</a>
    </div>
    <div id="container1">
        <div class="d-flex justify-content-end">
          <p>{{story.author}}</p>
        </div>
        <div class="d-flex justify-content-center">
          <p>{{story.text}}</p>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-sm-4 row" style="text-align: center;justify-content: center;">
              <div class="col-auto my-2">
                <form action="{% url 'true_story' story.pk %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary"   name="true_story_id" value="{{ story.id }}">True</button>
                </form>
              </div> 
                <p class="col-sm">{{total_true}}</p>
            </div>
            <div class="col-sm-4 row" style="text-align: center;justify-content: center;">
              <div class="col-auto my-2">
                <form action="{% url 'false_story' story.pk %}" method="POST" class="col-auto">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary" name="false_story_id" value="{{ story.id }}">False</button>
                </form>
              </div> 
              <p class="col-sm">{{total_false}}</p>
            </div>
        </div>
    </div>

    {% for comment in comments %}

      <div id="container2">
        <div class="d-flex justify-content-end"><p>{{comment.author}}</p></div>
        <div class="d-flex justify-content-center"><p>{{comment.text}}</p></div>
      </div>

    {% empty %} 

      <div id="container3">
        <div class="d-flex justify-content-center"><p>There are no comments yet.</p></div>
      </div>

    {% endfor %}
    

    <div class="d-flex justify-content-center" id="container4" style="color: white;">
        <form action="" method="POST" style="width: 70%;">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_text">Comment:</label>
            <textarea name="text" class="form-control" id="id_text" rows="4" maxlength="550" required=""></textarea>
          </div>
          <div class="col-sm">
            <p class="col-sm" style="margin-left: 50%;">{{ user.get_username}}</p>
          </div>
          <div class="col-auto my-2">
            <button type="submit" name="save_comment" class="btn btn-secondary" style="margin-left: 90%;">Save</button>
          </div>
        </form>
    </div>
{% endblock %}

story/templates/story/story_form.html
{% extends 'base.html' %}
{% block content %}
{% include 'nav.html' %}
<div id="container" style="background-color: black;">
    <form action="./" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_text">My story</label>
            <textarea name="text" class="form-control" id="id_text" rows="4" maxlength="2000" required=""></textarea>
          </div>
          <div class="form-check">
            <input type='hidden' value='{{ user.get_username}}' name='author' id="id_author">
            <input type='hidden' value='False' name='ans'>
            <input type="checkbox" class="form-check-input" name="ans" id="id_ans">
            <label class="form-check-label" for="id_ans">True?</label>
          </div>
          <div class="col-auto my-2">
            <button type="submit" class="btn btn-secondary" style="margin-left: 94%;">Save</button>
          </div>
</form>
</div>
{% endblock %}